# Generated by Django 5.0.6 on 2024-06-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_data', models.JSONField(default=dict)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Brak opisu')),
                ('status', models.CharField(choices=[('NEW', 'Nowy'), ('IN_PROGRESS', 'W toku'), ('RESOLVED', 'Rozwiązany'), ('DELETED', 'Usunięte')], default='NEW', max_length=11)),
            ],
        ),
    ]
